spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springjpa?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    driver-class-name: "com.mysql.jdbc.Driver"
    username: root
    password: tt@aec

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"

server:
  servlet:
    context-path: /api
#  =true&amp;serverTimezone=UTC&amp;useSSL=false"