spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dbprodutos?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false"
    driver-class-name: "com.mysql.jdbc.Driver"
    username: root
    password: tt@aec

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"


#  =true&amp;serverTimezone=UTC&amp;useSSL=false"